package com.kou.sbmm.entity;
// Generated 2019-5-3 8:33:56 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Spmmdb0002 generated by hbm2java
 */
@Entity
@Table(name = "spmmdb0002")
public class Spmmdb0002 implements java.io.Serializable {

	private Integer msgid;
	private Integer accid;
	private String name;
	private String msgtitle;
	private String msgcont;
	private Character msgpublictype;
	private Date createdatetime;

	public Spmmdb0002() {
	}

	public Spmmdb0002(String msgtitle) {
		this.msgtitle = msgtitle;
	}

	public Spmmdb0002(Integer accid, String name, String msgtitle, String msgcont, Character msgpublictype,
			Date createdatetime) {
		this.accid = accid;
		this.name = name;
		this.msgtitle = msgtitle;
		this.msgcont = msgcont;
		this.msgpublictype = msgpublictype;
		this.createdatetime = createdatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MSGID", unique = true, nullable = false)
	public Integer getMsgid() {
		return this.msgid;
	}

	public void setMsgid(Integer msgid) {
		this.msgid = msgid;
	}

	@Column(name = "ACCID")
	public Integer getAccid() {
		return this.accid;
	}

	public void setAccid(Integer accid) {
		this.accid = accid;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "MSGTITLE", nullable = false, length = 200)
	public String getMsgtitle() {
		return this.msgtitle;
	}

	public void setMsgtitle(String msgtitle) {
		this.msgtitle = msgtitle;
	}

	@Column(name = "MSGCONT", length = 65535)
	public String getMsgcont() {
		return this.msgcont;
	}

	public void setMsgcont(String msgcont) {
		this.msgcont = msgcont;
	}

	@Column(name = "MSGPUBLICTYPE", length = 1)
	public Character getMsgpublictype() {
		return this.msgpublictype;
	}

	public void setMsgpublictype(Character msgpublictype) {
		this.msgpublictype = msgpublictype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATETIME", length = 26)
	public Date getCreatedatetime() {
		return this.createdatetime;
	}

	public void setCreatedatetime(Date createdatetime) {
		this.createdatetime = createdatetime;
	}

}
